### CREATE POST
POST http://localhost:8080/api/subSetting/jonathan/post
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "postName": "Whats the best genre of music?",
  "description": "And what makes it so nice to you?"
}

### LIKE POST
POST http://localhost:8080/api/subSetting/jonathan/post/30/vote
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "voteType": "DOWNVOTE"
}